#ifndef CONSTANTS_H
#define CONSTANTS_H

#include "config.h"
#include <FastLED.h>

// Network constants
#define PACKET_TIMEOUT_MS 50
#define MAX_CONNECTION_LOSS_MS 5000

// Command constants
#define GET_FRAME_COMMAND "GF:"

// Status constants
#define STATUS_LED_COUNT 3
#define STATUS_CONNECTING CRGB::Orange

// Animation constants
#define MILLIS_PER_FRAME 1000 / TARGET_FPS

// LED strip constants
#define TOTAL_LED_COUNT STAGE_PROP_COUNT * LED_COUNT
#define BYTES_PER_LED 3
#define HEADER_SIZE 1
#define LED_BUFFER_SIZE HEADER_SIZE + BYTES_PER_LED * TOTAL_LED_COUNT

// Network event constants
#if defined(ESP8266)
    #define EVENT_CONNECTED WIFI_EVENT_STAMODE_CONNECTED
    #define EVENT_GOT_IP WIFI_EVENT_STAMODE_GOT_IP
    #define EVENT_DISCONNECTED WIFI_EVENT_STAMODE_DISCONNECTED
#elif defined(ESP32)
    #define EVENT_CONNECTED SYSTEM_EVENT_STA_CONNECTED
    #define EVENT_GOT_IP SYSTEM_EVENT_STA_GOT_IP
    #define EVENT_DISCONNECTED SYSTEM_EVENT_STA_DISCONNECTED
#endif

#endif CONSTANTS_H
